### PR TITLE
JSlix Image Library - Bug Fix #472

### LINKED ISSUE #472: JSlix Renderer - Data Integrity Error
While checking JSlix, realized that there was an error in how data was being ordered in the system. Within the setup function, all the manipulations would happen to the second image all at the same time. Investigating what can be causing the issue.

### PR DESCRIPTION
**Pull request by ctomni231**
- Fixes issue #472, leaving data integrity intact
- Adds colored units to the map for two different armies
- Adds some quality of life changes to performance.js and supporting 
classes

### CODE REVIEW

File: new_core/config/debugPages.js [hunk 1]
```diff
@@ -2,7 +2,8 @@ export const MAIN_INFO = {
   name: "Performance",
   data: {
     row1: {
-      col1: [ "FPS", "performance.gameloop.fps" ],
+      col1: [ "TFPS", "performance.gameloop.tfps" ],
+      col2: [ "JFPS", "performance.gameloop.jfps"]
```
Comment (Tapsi) [inline new_core/config/debugPages.js]: what's the difference between tfps and jfps. I would suggest to use better property names here. Even FPS is not good as name, but at least well known.

File: new_core/performance.js [hunk 2]
```diff
@@ -9,7 +9,11 @@ export function startMeasure (measureId) {
       lastDuration: 0,
       averageDuration: 0,
       lastTimestamp: -1,
-      fps: 0
+      count: 0,
```
Comment (Tapsi) [inline new_core/performance.js]: is count the same as number of iterations? if yes, then we should use the existing variable here.

File: new_core/screens/initial.js [hunk 3]
```diff
@@ -57,7 +57,7 @@ export function render (canvas, ctx) {
   ctx.fillRect(0,0,canvas.width,canvas.height)
 
   // This draws the image onto the screen
-	ctx.drawImage(jslix.getImg(0), 90, 120, 200, 20)
+	ctx.drawImage(jslix.getImg(0), SCREEN_WIDTH - 210, SCREEN_HEIGHT - 30, 200, 20)
   //ctx.drawImage(jslix.quickImage("../image/mobile/cwttitle.png"), 10, 120, 200, 20)
```
Comment (Tapsi) [inline new_core/screens/initial.js]: no need to fear the deletion of comments.  the code is persisted in the history, so in my opinion there is no reason to leave it as comment in the code.

see: http://geekswithblogs.net/MarkPearl/archive/2011/09/12/commenting-code-is-an-anti-pattern.aspx

File: new_core/config/debugPages.js (hunk 1 above)
Comment (ctomni231) [reply new_core/config/debugPages.js]: They both represent the same data, calculating frames per second

TFPS = Tapsi Frames Per Second, which gets the delta time each frame
JFPS = JSRulz Frame Per Second, which gets the frames each second

Both are useful for different reasons, but I definitely use jfps for impact code. I leave tfps, because it is useful for figuring out an average of fps over time. We've been back and forth on this (taking it out, putting it back in). Can a compromise be made, maybe?

Comment (Tapsi) [reply new_core/config/debugPages.js]: ok, I have a big smile on my face. :D

File: new_core/performance.js (hunk 2 above)
Comment (ctomni231) [reply new_core/performance.js]: Count does count iterations, but it resets it every time a second is reached.

File: new_core/config/debugPages.js (hunk 1 above)
Comment (Tapsi) [reply new_core/config/debugPages.js]: but tfps is not the delta time. if I am not mistaken, then you mean it will be calculated every tick right ?

File: new_core/screens/initial.js (hunk 3 above)
Comment (ctomni231) [reply new_core/screens/initial.js]: Yeah, I'll edit this in another commit to this branch to get rid of these extra bits of information. I thought I caught them all, but this must have came back when I merged the code with master :(

File: new_core/performance.js (hunk 2 above)
Comment (Tapsi) [reply new_core/performance.js]: isn't numberOfIterations % 1000 === 0 the same ? just try to figure out if we can prevent having two variables here

File: new_core/config/debugPages.js (hunk 1 above)
Comment (ctomni231) [reply new_core/config/debugPages.js]: Yeah, it'll be calculated each tick

Comment (Tapsi) [reply new_core/config/debugPages.js]: okay we should remove tfps , since we have delta as model variable. JFPS should be renamed to FPS then. I think you only want to see bad frames (high delta) and a flattened FPS.

Comment (Tapsi) [reply new_core/config/debugPages.js]: IMHO jfps is definitely better than the current FPS variable

File: new_core/screens/initial.js (hunk 3 above)
Comment (Tapsi) [reply new_core/screens/initial.js]: no problem 😁

File: new_core/performance.js (hunk 2 above)
Comment (ctomni231) [reply new_core/performance.js]: That is a good solution

File: new_core/config/debugPages.js (hunk 1 above)
Comment (ctomni231) [reply new_core/config/debugPages.js]: Yeah, but they both have their uses. Like, you can see which frames spike exactly with tfps. I learned to use both to get a good idea of the game performance without having to crack open an editor and look at two debug windows at once. So much information about profiling from just those two bits of information

File: new_core/performance.js (hunk 2 above)
Comment (ctomni231) [reply new_core/performance.js]: Wait, I take it back. Count resets every time the frame duration is over 1000 milliseconds. That isn't the same as the numberOfIterations, because that number will continuously move forward forever. I can probably achieve this with a storage variable instead. It'll save us one line of code

measureData.jfps = measureData.numberOfIterations - measureData.count;
measureData.count = measureData.numberOfIterations;

**Comment by ctomni231** [comment]
Performed a lot of the fixes discussed in our conversations
- Got rid of the comment in initial.js
- Re-purposed count to store iterations instead of counting them
- Created FPS and FPT for the debug console

File: new_core/performance.js (hunk 2 above)
Comment (ctomni231) [reply new_core/performance.js]: Didn't get rid of count, but did repurpose it to utilize the numberOfIterations instead. Just need a small persistent storage variable somewhere I can reach it. Closing this for now, start a new conversation if this solution is rough around the edges.

File: new_core/config/debugPages.js (hunk 1 above)
Comment (Tapsi) [reply new_core/config/debugPages.js]: I'll remove it later on. Duplicates the delta value in a different format.
